version: '3.9'

networks:
  arlocal:
    driver: bridge

services:
  cassandra:
    image: 'bitnami/cassandra:3.11.10'
    container_name: cassandra
    ports:
      - '9042:9042'
      - '7199:7199'
      - '7000:7000'
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - CASSANDRA_CLUSTER_NAME="arweave-community-gateway"
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
      - CASSANDRA_JMX_PORT_NUMBER=7199
      - CASSANDRA_CQL_PORT_NUMBER=9042
      - CASSANDRA_HOST=cassandra
      - HEAP_NEWSIZE=600M 
      - MAX_HEAP_SIZE=1024M
    volumes: 
      - ./data/cassandra:/bitnami
    networks:
      - arlocal

  gateway:
    container_name: gateway
    build: .
    ports:
      - '80:3000'
    environment: 
      - CASSANDRA_CONTACT_POINTS=["cassandra"]
    links:
      - cassandra
    depends_on:
      cassandra:
        condition: service_healthy
    networks:
      - arlocal