# This is a basic workflow to help you get started with Actions

name: Eslint check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '16'
    - name: Install modules
      run: yarn install --ignore-engines
    - name: Run ESLint
      run: yarn run --ignore-engines eslint . --ext .js,.jsx,.ts,.tsx
