name: "CI Test+Lint"
on:
  pull_request:
    branches: ["**"]
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: arweave-gateway-cassandra
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: test
        run: |
          sudo mkdir -p /var/lib/cassandra/data/data
          sudo mkdir -p /var/lib/cassandra/data/commitlog
          sudo chmod -R +666 /var/lib/cassandra/data
          nix-shell --pure nix/test.nix
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: arweave-gateway-cassandra
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: lint
        run: nix-shell --pure nix/lint.nix
